[application]
name = "gloo_solana_dioxus_app"
# Web-focused configuration
default_platform = "web"

[web.app]
title = "🌊 gloo_solana Dioxus Example"

[web.resource]
# CSS file and other resources
style = [
    "public/styles.css",
]

[web.resource.dev]
# Development configuration
style = [
    "public/styles.css",
]

[web.watcher]
# Watch for changes in source files
reload_html = true
watch_path = ["src"]

[[web.proxy]]
# Proxy backend requests for Solana RPC - proper API endpoint
backend = "http://127.0.0.1:8899/api"
