[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "CounterProgram111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
auto-deploy = "cargo run --bin surfpool_deploy -- --start"
demo-calls = "cargo run --bin surfpool_deploy -- --demo-calls"

[test.validator]
url = "http://127.0.0.1:8899"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.validator.account]]
address = "CounterProgram111111111111111111111111111111"
filename = "target/deploy/counter.so"

[workspace]
types = "programs/counter/src/types/"

# Surfpool auto-deployment configuration
[surfpool]
endpoint = "http://127.0.0.1:8899"
websocket = "ws://127.0.0.1:8900"
commitment = "confirmed"
preflight = false

# Enhanced auto-deployment settings with IDL integration
[auto_deploy]
enabled = true
deploy_on_startup = true
generate_idl = true
create_program_clients = true
airdrop_users = true

# User airdrop configuration - use single local keypair
[airdrop]
enabled = true
amount_per_user = 10000000000  # 10 SOL in lamports
skip_preflight = true

# Define users who will receive airdrops and use the programs
[[airdrop.users]]
keypair = "~/.config/solana/id.json"
name = "Local Developer"
role = "developer"
balance = 0
programs_to_use = ["counter"]

# IDL generation settings
[idl]
output_dir = "target/idl"
include_accounts = true
include_instructions = true
include_types = true
format = "json"

# Program client settings
[clients]
generate_typescript = true
generate_rust = true
output_dir = "target/clients"
